@TM:1419709182
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\proasic3.v":1163:7:1163:9|Synthesizing module GND
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\proasic3.v":1283:7:1283:9|Synthesizing module INV
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\proasic3.v":1864:7:1864:9|Synthesizing module VCC
@N: CG364 :"C:\Actelprj\3116004982_zsy\component\work\zsy_cp1\zsy_cp1.v":5:7:5:13|Synthesizing module zsy_cp1
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\HC161.v":1:7:1:11|Synthesizing module HC161
@N: CG179 :"C:\Actelprj\3116004982_zsy\hdl\HC161.v":18:19:18:22|M
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\HC4511.v":2:7:2:12|Synthesizing module HC4511
@W: CL118 :"C:\Actelprj\3116004982_zsy\hdl\HC4511.v":11:7:11:8|M
@N: CG179 :"C:\Actelprj\3116004982_zsy\hdl\HC4511.v":13:25:13:29|M
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\HC85.v":1:7:1:10|Synthesizing module HC85
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":3:7:3:14|Synthesizing module test_cp1
@W: CG730 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":3:7:3:14|M
@W: CG133 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":4:10:4:10|M
@W: CG133 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":4:12:4:12|M
@W: CG133 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":5:5:5:6|M
@W: CL168 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":7:9:7:13|M
@W: CG532 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":8:1:8:7|M
@W: CG294 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":14:0:14:5|M
@W: CG532 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":15:0:15:6|M
@W: CG532 :"C:\Actelprj\3116004982_zsy\hdl\test_cp1.v":21:0:21:6|M
