@TM:1419709841
@N: FP130 :"":0:0:0:-1|Promoting Net CP_c on CLKBUF  CP_pad 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock zsy_cp1|CP with period 10.00ns. A user-defined clock should be declared on object "p:CP"
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\proasic3.v":1163:7:1163:9|Synthesizing module GND
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\proasic3.v":1283:7:1283:9|Synthesizing module INV
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\proasic3.v":1864:7:1864:9|Synthesizing module VCC
@N: CG364 :"C:\Actelprj\3116004982_zsy\component\work\zsy_cp1\zsy_cp1.v":5:7:5:13|Synthesizing module zsy_cp1
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\HC161.v":1:7:1:11|Synthesizing module HC161
@N:  :"c:\actelprj\3116004982_zsy\hdl\hc161.v":10:1:10:6|M
@N: CG179 :"C:\Actelprj\3116004982_zsy\hdl\HC161.v":18:19:18:22|M
@N: BN116 :"c:\actelprj\3116004982_zsy\hdl\hc161.v":20:1:20:6|M
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\HC4511.v":2:7:2:12|Synthesizing module HC4511
@W: CL118 :"C:\Actelprj\3116004982_zsy\hdl\HC4511.v":11:7:11:8|M
@N: MO106 :"c:\actelprj\3116004982_zsy\hdl\hc4511.v":11:7:11:8|M
@W: MO129 :"c:\actelprj\3116004982_zsy\hdl\hc4511.v":11:7:11:8|M
@N: CG179 :"C:\Actelprj\3116004982_zsy\hdl\HC4511.v":13:25:13:29|M
@N: CG364 :"C:\Actelprj\3116004982_zsy\hdl\HC85.v":1:7:1:10|Synthesizing module HC85
@N: MF179 :"c:\actelprj\3116004982_zsy\hdl\hc85.v":9:10:9:21|M
@N: MF179 :"c:\actelprj\3116004982_zsy\hdl\hc85.v":9:10:13:26|M
